version: '3.8'

services:
  mineru-vlm-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: mineru-vlm-api
    ports:
      - "8000:8000"
    volumes:
      - ./output:/app/output
      - ./logs:/app/logs
      - ./temp:/app/temp
    environment:
      - MINERU_MODEL_SOURCE=local
      - LOG_LEVEL=info
      - PORT=8000
      - HOST=0.0.0.0
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 120s
    networks:
      - mineru-network

  # Optional: SGLang server for vlm-sglang-client backend
  sglang-server:
    image: lmsysorg/sglang:v0.4.7-cu124
    container_name: sglang-server
    ports:
      - "30000:30000"
    environment:
      - CUDA_VISIBLE_DEVICES=0
    command: >
      python -m sglang.launch_server
      --model-path opendatalab/MinerU2.0-2505-0.9B
      --host 0.0.0.0
      --port 30000
      --tp-size 1
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:30000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    networks:
      - mineru-network
    profiles:
      - sglang  # Use with: docker-compose --profile sglang up

networks:
  mineru-network:
    driver: bridge

volumes:
  output:
  logs:
  temp: 